# Configuration file to set arguments for GCsnap.
# To change argument, change: value: entry.
# E.g. value: 1 to value: 2
# ---------------------------------------

out_label:
    value: default
    type: str
    help: Name of output directory. If default, name of the input file.

ncbi_api_key:
    value: None
    type: str
    help: The key for NCBI API, which allows for up to 10 queries per second to NCBI databases. Shall be obtained after obtaining an NCBI account.

n_cpu: 
    value: 4
    type: int
    help: Number of cores to use.

n_flanking:
    value: 4
    type: int
    help: Number of flanking sequences to take on each side.
n_flanking5:
    value: 4
    type: int
    help: Number of flanking sequences to take on 5' end.
n_flanking3:
    value: 4
    type: int
    help: Number of flanking sequences to take on 3' end.
exclude_partial:
    value: true
    type: bool
    help: Exclude partial operon/genomic_context blocks. If turned off, partial cases will still be ignored to get the most common genomic features.

clans_patterns:
    value: None
    type: str
    help: Patterns to identify the clusters to analyse. They will be used to select the individual clusters in the clans map to analyse.
clans_file:
    value: None
    type: str
    help: Used only for advanced interactive output representation (Clans file if the input is a clans file and -operon_cluster_advanced is set to True).

overwrite_config:
    value: false
    type: bool
    help: Overwrite the argument value in config file with CLI value.